#!/usr/bin/env python3
"""Command-line client for MaryTTS

A command line client for the HTTP server of the MaryTTS Text-To-Speech System.
"""
#pylint: disable = invalid-name

import sys

import requests

from marytts_cli.arguments import setup_argparser
from marytts_cli.client import MaryTTSClient

def main():
    """Initialize, run query, output response and exit"""
    args = setup_argparser().parse_args()
    marytts_client = (
        MaryTTSClient(args.url)
        if args.url
        else MaryTTSClient()
    )

    if args.audio:
        marytts_client.audio()
    if args.input:
        marytts_client.input_type(args.input)
    if args.locale:
        marytts_client.locale(args.locale)
    if args.output:
        marytts_client.output_type(args.output)
    if args.voice:
        marytts_client.voice(args.voice)

    stdin_data = sys.stdin.read()
    try:
        query_response = marytts_client.query(stdin_data)
        if not query_response.ok:
            raise requests.exceptions.HTTPError()
        sys.stdout.buffer.write(query_response.content)
        sys.stdout.flush()
        sys.exit(0)
    except requests.exceptions.RequestException:
        sys.stderr.write('Error: Request to MaryTTS HTTP server failed\n')
        sys.stderr.flush()
        sys.exit(1)

if __name__ == '__main__':
    main()
