.TH marytts-cli "1" Manual
.SH NAME
marytts-cli
.SH SYNOPSIS
.B marytts-cli
[-h] [--audio AUDIO] [--input INPUT] [--locale LOCALE] [--output OUTPUT] [--url URL] [--voice VOICE]
.SH DESCRIPTION
A command\-line client for the HTTP server of the MaryTTS Text\-To\-Speech
System.
.SH OPTIONS

.TP
\fB\-\-audio\fR AUDIO
set format of MaryTTS audio output

.TP
\fB\-\-input\fR INPUT
set type of MaryTTS input

.TP
\fB\-\-locale\fR LOCALE
set identifier of Locale

.TP
\fB\-\-output\fR OUTPUT
set type of MaryTTS output

.TP
\fB\-\-url\fR URL
set request URL

.TP
\fB\-\-voice\fR VOICE
set name of MaryTTS voice

.SH AUTHORS
.B marytts\-cli
was written by trevor <trevor@destroyed.today>.
.SH DISTRIBUTION
The latest version of marytts\-cli may be downloaded from
.UR https://github.com/x3a/marytts\-cli
.UE
