.TH marytts-cli "1" Manual
.SH NAME
marytts-cli
.SH SYNOPSIS
.B marytts-cli
[-h] [-a AUDIO] [-i TYPE] [-l LOCALE] [-o TYPE] [-t SECONDS] [-u URL] [-v VOICE]
.SH DESCRIPTION
A command\-line client for the HTTP server of the MaryTTS Text\-To\-Speech
System.
.SH OPTIONS

.TP
\fB\-a\fR AUDIO, \fB\-\-audio\fR AUDIO
set format of MaryTTS audio output

.TP
\fB\-i\fR TYPE, \fB\-\-input\fR TYPE
set type of MaryTTS input

.TP
\fB\-l\fR LOCALE, \fB\-\-locale\fR LOCALE
set identifier of Locale

.TP
\fB\-o\fR TYPE, \fB\-\-output\fR TYPE
set type of MaryTTS output

.TP
\fB\-t\fR SECONDS, \fB\-\-timeout\fR SECONDS
set request timeout

.TP
\fB\-u\fR URL, \fB\-\-url\fR URL
set request URL

.TP
\fB\-v\fR VOICE, \fB\-\-voice\fR VOICE
set name of MaryTTS voice

.SH AUTHORS
.B marytts\-cli
was written by trevor <trevor@destroyed.today>.
.SH DISTRIBUTION
The latest version of marytts\-cli may be downloaded from
.UR https://github.com/x3a/marytts\-cli
.UE
